### ISSUE TITLE
NPM lockfile error

### ISSUE THREAD

**Issue by Cdddo** [HaaLeo/publish-vscode-extension#20]
# Description
Followed the steps to set it up but I get this error when trying to run
```
The `npm ci` command can only install with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate a package-lock.json file, then try again.
```
I'm unfamiliar with npm and github actions, so I'm sure I must have missed a step in how to configure this.

**Comment by HaaLeo** [comment]
Hi @Cdddo thx for opening this issue. 
The error you report is not related to this GitHub action but to your project setup. Ensure you commit your `package-lock.json` file with your repository. Then the command `npm ci` will succeed.
However, if you do not have any node modules as dependencies you can omit the command in the config of your GitHub action.

For further details I recommend you to check out the [official documentation](https://code.visualstudio.com/api/get-started/your-first-extension) to get started developing VS Code extensions
