### ISSUE TITLE
Failed request: 401 on Publishing Extension

### ISSUE THREAD

**Issue by stephenasuncionDEV** [HaaLeo/publish-vscode-extension#25]
| publish-vscode-extension Version | Operating System |
| -------------------------------------- | ---------------- |
|                   v1.0.7                             |         Windows  |

# Description
The extension fails on publishing the extension on the visual studio marketplace.

## Expected Behavior
The extension should publish the .vsix file to Visual Studio Marketplace

## Actual Behavior
It fails on `Publish to Visual Studio Marketplace` step. Packaging the extension was successful but publishing isn't.

# Steps to Reproduce
Could be reproduced by forking https://github.com/stephenasuncionDEV/gencomp

# Context
Notable Changes:
- Instead of `npm ci`, I did `yarn install`
- VS_ACCESS_TOKEN secret has all the scope

Action:
<details>
<pre>
<code>
name: CI to VS Marketplace
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1.0.7
        with:
          pat: ${{ secrets.VS_ACCESS_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
</code>
</pre>
</details>

Error:
![image](https://user-images.githubusercontent.com/73958774/195536880-ccc2aaa9-48f9-4aab-b1a0-eb00c92094eb.png)

**Comment by HaaLeo** [comment]
Hi @stephenasuncionDEV  thx for your contribution. Probably this issue occurs because the PAT is missing some access rights and _not_ due to the implementation of this GitHub action. It sounds to me this is probably a duplicate of #4 or #21

**Comment by stephenasuncionDEV** [comment]
> Hi @stephenasuncionDEV thx for your contribution. Probably this issue occurs because the PAT is missing some access rights and _not_ due to the implementation of this GitHub action. It sounds to me this is probably a duplicate of #4 or #21

Hello,

Apologies, I did not see the closed issues. Turns out I did not have Marketplace scope with the access token.
