### ISSUE TITLE
add _option_ to publish to GitHub release

### ISSUE THREAD

**Issue by GitMensch** [HaaLeo/publish-vscode-extension#28]
**Is your feature request related to a problem? Please describe.**
Many people don't upload artifacts on GitHub; but as a "manual" and "backup" approach this would be very useful.
If there is a vsix uploaded, then often the vsix was "extra built" (so isn't necessary identical to the uploaded one).

**Describe the solution you'd like**
Make it easy for users of this action to publish the same vsix which is published to the market places also to GH release.

**Describe alternatives you've considered**
Setup a separate action that builds the vsix and uploads it, but as most is done nicely here already...

**Additional context**
[This action](https://github.com/PDConSec/vsc-print/pull/121/files) does it the other way around: build the vsix, upload to GH, then download from there and upload to the market places.

**Comment by HaaLeo** [comment]
Hi @GitMensch, thx for this feature request. IMHO, I think this is _out of scope_ for this GitHub action and can be easily achieved by combining this GitHub action with multiple other ones like in your example. Another example is the one I have linked in the README.md ([link](https://github.com/HaaLeo/vscode-timing/blob/master/.github/workflows/cicd.yml#L1)).

As of now I do not plan to integrate such a feature in the this action. However, if this feature request receives decent amount of upvotes I'll probably reconsider.

**Comment by GitMensch** [comment]
I didn't found a hint about that in this project's README. Can you please recheck and add it?
