### ISSUE TITLE
Renaming of vsce to @vscode/vsce

### ISSUE THREAD

**Issue by lsaudon** [HaaLeo/publish-vscode-extension#30]
I saw this in the release note of version 1.74.

[Renaming of vsce to @vscode/vsce](https://code.visualstudio.com/updates/v1_74#_renaming-of-vsce-to-vscodevsce)

> The [vsce](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce) tool, VS Code's extension manager, has been renamed to [@vscode/vsce](https://www.npmjs.com/package/@vscode/vsce). This is a breaking change for anyone using the tool as a library. The CLI tool is still called vsce and can be installed via npm install -g @vscode/vsce.

**Comment by HaaLeo** [comment]
Released with v1.2.0
