### ISSUE TITLE
Doesn't work with yarn version 2+ with PnP

### ISSUE THREAD

**Issue by sdankel** [HaaLeo/publish-vscode-extension#34]
| publish-vscode-extension Version | Operating System |
| -------------------------------------- | ---------------- |
|                   1                    |          osx     |

# Description

It fails at `yarn list --prod --json`, because yarn 2 and 3 don't have `yarn list`

This is preventing users from being able to upgrade to newer versions of yarn while using this action.

I see this is a problem in the underlying [vsce](https://github.com/microsoft/vscode-vsce/blob/57112fd0efbc53a68f8aa711be12cd080b3eed48/src/npm.ts#L160) package as well. https://github.com/microsoft/vscode-vsce/issues/517

## Expected Behavior

It will need to check the version of yarn and use the appropriate commands for the yarn version. Either that, or change the `yarn` argument from a boolean to a number or string to represent the version.

## Actual Behavior

It fails, [example](https://github.com/FuelLabs/sway-vscode-plugin/actions/runs/3993434997)

# Steps to Reproduce
1. Run it on any package that is using yarn version > 1 with PnP

**Comment by sdankel** [comment]
It looks like a workaround for this is to pass `dependencies: false` to vsce: https://github.com/microsoft/vscode-vsce/issues/439

This bypasses the `yarn list` check which is fine for yarn v2+ with pnp (no `node_modules`). I propose we add an option to this action like `dependencies: boolean`, similar to vsce.

**Comment by HaaLeo** [comment]
Hi @sdankel thx for your contribution. I will take a look as soon as possible :)

**Comment by HaaLeo** [comment]
published with v1.3.0
