### ISSUE TITLE
support pass args to vsce

### ISSUE THREAD

**Issue by tjx666** [HaaLeo/publish-vscode-extension#36]
I need set `--no-dependencies` when publish extension with pnpm

details here: https://github.com/microsoft/vscode-vsce/issues/421#issuecomment-1038911725

failed github action: https://github.com/tjx666/awesome-vscode-extension-boilerplate/actions/runs/4269744506/jobs/7433113168

**Comment by HaaLeo** [comment]
duplicate of #34
