### ISSUE TITLE
Add support for --target

### ISSUE THREAD

**Issue by degrammer** [HaaLeo/publish-vscode-extension#37]
**Is your feature request related to a problem? Please describe.**
OpenVSX added support for publishing the extension to specific platforms via --target:
Example:
`ovsx ... --target linux-x64`

**Describe the solution you'd like**
Is there any plan to support such an option? Based on my findings is a matter of adding the command [here](https://github.com/HaaLeo/publish-vscode-extension/blob/master/src/main.ts#L44-L56), but I wanted to confirm if this was discussed before or if there is any reason isn't supported.

**Describe alternatives you've considered**
One alternative is to use ovsx package directly and execute a script from the GitHub Action 

**Additional context**
This was released a while back at https://github.com/eclipse/openvsx/issues/503

**Comment by HaaLeo** [comment]
Released with [`v1.5.0`](https://github.com/HaaLeo/publish-vscode-extension/releases/tag/v1.5.0). Thx @alexravenna & @degrammer for your contribution.
