### ISSUE TITLE
Failed request (401)

### ISSUE THREAD

**Issue by anteprimorac** [HaaLeo/publish-vscode-extension#4]
Thank you for making this GitHub action.

I keep getting `Error: Failed request: (401)`, but I am sure that my PAT is correct and has correct permissions. Is there a way of debugging this request?

**Comment by HaaLeo** [comment]
Hi @anteprimorac, thank you for opening the issue. 
`401` in general means the request is [unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401). The VS Code team lists the 401 error in their [common questions](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#i-get-403-forbidden-or-401-unauthorized-error-when-i-try-to-publish-my-extension) section. So maybe you want to go to the [manage page](https://marketplace.visualstudio.com/manage) and double check that your PAT has the correct privileges and is not expired yet.

**Comment by anteprimorac** [comment]
Hi @HaaLeo , I was able to resolve an issue with the PAT. I had to change the organization to "All accessible organizations" to make it work, but on vscode docs, it says to not set it to that option which is a little bit misleading. But anyway, thank you.

**Comment by danielo515** [comment]
I had to make the same adjusts. Thanks.

**Comment by Antyos** [comment]
> Hi @HaaLeo , I was able to resolve an issue with the PAT. I had to change the organization to "All accessible organizations" to make it work, but on vscode docs, it says to not set it to that option which is a little bit misleading. But anyway, thank you.

I too, had to make the same adjustments. I misread it too at first, but I think the common questions is saying "a common mistake is to ***not*** select the **All accessible organizations** option", meaning that you ***are*** supposed to select it. It could probably be worded better.
