### ISSUE TITLE
Documentation states that preRelease is not supported by Open VSX

### ISSUE THREAD

**Issue by lukaszsamson** [HaaLeo/publish-vscode-extension#42]
It is supported since 0.4.0 and currently the action depends on 0.8.0

https://github.com/eclipse/openvsx/blob/63eae3eeb2b60edd5054f5c0fe3301ed4b8a9877/cli/CHANGELOG.md?plain=1#L65

**Comment by HaaLeo** [comment]
Hi @lukaszsamson good catch. I'll update that with the next release :)
