### ISSUE TITLE
Bump node version

### ISSUE THREAD

**Issue by pokey** [HaaLeo/publish-vscode-extension#50]
I'm getting deprecation warnings when using this GitHub action:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: HaaLeo/publish-vscode-extension@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

I think it just requires a change to the following line?

https://github.com/HaaLeo/publish-vscode-extension/blob/f0b46c74abc834fe267e8d320be7c4bf56179f06/action.yml#L67

**Comment by HaaLeo** [comment]
Hi @pokey, 
thx for reporting this issue. I have addressed this with release v1.6.0.
