### ISSUE TITLE
Extension manifest not found: node_modules/node_modules/fast-deep-equal/package.json

### ISSUE THREAD

**Issue by InTheCloudDan** [HaaLeo/publish-vscode-extension#51]
| publish-vscode-extension Version | Operating System |
| -------------------------------------- | ---------------- |
|    @1 and @1.6.0                                   |   Linux               |

# Description

Just started seeing `Extension manifest not found: node_modules/node_modules/fast-deep-equal/package.json` loading the vsix up in VSIX viewer extension and the package.json is definitely there.

I tried updating to `1.6.0` but the running logs(below) still say `1.5.0`.

Nothing changed in extension packaging from a build that worked 3 days ago.

## Expected Behavior

Build would complete

## Actual Behavior

It fails with `Extension manifest not found: node_modules/node_modules/fast-deep-equal/package.json`

# Steps to Reproduce

1. 
2. 
3. 

# Context
<details><pre><code>

with:
    pat: ***
    registryUrl: https://marketplace.visualstudio.com
    yarn: true
    preRelease: true
    packagePath: ./
    dryRun: false
    noVerify: false
    dependencies: true
    skipDuplicate: false
Specifically, running GitHub Action HaaLeo/publish-vscode-extension@v1.5.0.
Package the Extension
  Start packaging the extension.
  Executing prepublish script 'yarn run vscode:prepublish'...
  yarn run v1.22.21
  warning launchdarkly@4.99.52: The engine "vscode" appears to be invalid.
  $ webpack --mode production
  asset extension.js 8[3](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:3)3 KiB [emitted] [minimized] (name: main) 2 related assets
  asset 713.extension.js [4](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:4).2[5](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:5) KiB [emitted] [minimized] 1 related asset
  orphan modules 55.9 KiB [orphan] 37 modules
  runtime modules 2.44 KiB 8 modules
  modules by path ./node_modules/ 2.1[6](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:6) MiB
    javascript modules 2.15 MiB 43[7](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:7) modules
    json modules 6.63 KiB
      modules by path ./node_modules/ajv/lib/ 3.12 KiB 2 modules
      + 2 modules
  modules by path ./src/ 2[8](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:8)1 KiB 40 modules
  optional modules 126 bytes [optional]
    external "worker_threads" 42 bytes [optional] [built] [code generated]
    external "node:process" 42 bytes [optional] [built] [code generated]
    external "node:stream/web" 42 bytes [optional] [built] [code generated]
  + 21 modules
  webpack 5.8[9](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:9).0 compiled successfully in [13](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:14)717 ms
  Done in [14](https://github.com/launchdarkly/ld-vscode/actions/runs/7755698217/job/21151596703#step:11:15).38s.
Error: Extension manifest not found: node_modules/node_modules/fast-deep-equal/package.json
</code></pre></details>

**Comment by HaaLeo** [comment]
Hi @InTheCloudDan thx for reporting this. We his could be a regression with v1.6.0 
Can you pls try to use explicitly v1.5.0 to reproduce the issue?

**Comment by HaaLeo** [comment]
I think there's a bug causing it to log always v1.5.0 instead of v1.6.0. Can you say when it failed first yesterday? That would help me to check whether it was before or after I have deployed v1.6.0.

**Comment by InTheCloudDan** [comment]
`13 hours ago`, sorry can't find exact time stamp. Ahh ok, I'll try explicitly setting `v1.5.0` and double check.

**Comment by HaaLeo** [comment]
I just published v1.6.1 which reverts the action's build target back to es6. Could you give it a try again?

**Comment by rtetley** [comment]
I have the same problem, even after specifying v1.6.1
<img width="725" alt="Screenshot 2024-02-13 at 10 50 24" src="https://github.com/HaaLeo/publish-vscode-extension/assets/32383664/ef361401-5dc5-459e-b0a6-c659019f30bd">

**Comment by HaaLeo** [comment]
@rtetley thx for bringing this up again. It seems this is a regression of vsce v2.23.0 (microsoft/vscode-vsce#928). Please endorse the upstream package to fix this.

I'll consider to revert the package version in the meantime. However, I cannot name any ETA for this.

**Comment by HaaLeo** [comment]
So apparently I managed to squeeze in the fix within my lunch break. I hope reverting vsce to v2.22.0 (within the action's v1.6.2 release) fixes this for now.

Feel free to comment if that's not the case then I'll reopen the issue.

**Comment by rtetley** [comment]
Seems to be working again ! Thanks a lot ! :-)
